version: '3.8'
services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    networks:
      - my_network    
    restart: always

  app:
    tty: true
    working_dir: /home/app
    build: .
    environment:
      NODE_ENV: development
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
    ports:
      - "4000:4000"
    depends_on:
      - dynamodb
    networks:
      - my_network
networks:
  my_network:
    driver: bridge

volumes:
 data:
